### ISSUE TITLE
Compilation error with 1.0.2

### ISSUE THREAD

**Issue by Duraiamuthan** [Naituw/WBWebViewConsole#6]
I tried to build it as _Dyanmic Framework_ and

I got 'NSDictionary+Accessors/NSDictionary+Accessors.h' file not found
in WBJSBridgeMessage.m and WBWebViewConsoleUserPromptCompletionController.m

Here is the POD file

```
use_frameworks!
pod 'WBWebViewConsole', '~> 1.0.2’
```

**Comment by Duraiamuthan** [comment]
_**Fix:**_
Replacing this the following header import in **_WBJSBridgeMessage.m_** and _**WBWebViewConsoleUserPromptCompletionController.m**_
`#import <NSDictionary+Accessors/NSDictionary+Accessors.h>`
with this
`#import "NSDictionary+Accessors.h"`
fixed the issue

**Comment by Duraiamuthan** [comment]
As I am not _collobrator_ I couldn't re-open issue #5  that's closed by you(collobrator) and so I raised the new issue here.

**Comment by Naituw** [comment]
Hi,

I fixed this issue and pushed some changes to master branch. Those commits also removed all dependencies for WBWebViewConsole.

Please (temporary) change your Podfile declaration to

`pod 'WBWebViewConsole', :git => 'https://github.com/Naituw/WBWebViewConsole.git'`

and try again.

**Comment by Duraiamuthan** [comment]
Works fine and nice to see _WBWebViewConsole_ without _dependencies_ 👍
